db.url=jdbc:mysql://kodama.proxy.rlwy.net:16795/railway?useSSL=false&allowPublicKeyRetrieval=true
db.user=root
db.password=bFmbqrOpOaWXfPoBfGRpdiaGPYOsNwtE
upstash.host=intent-ghost-91758.upstash.io
upstash.port=6379
upstash.password=gQAAAAAAAWZuAAIgcDJhYzNiYjRjZTVmMjQ0ZjBjYWU3ZDdiNTg0ODczMjQ1Yw